### ISSUE TITLE
http/2 false positives?

### ISSUE THREAD

**Issue by bortels** [trailofbits/twa#20]
So - it looks like http/2 servers are giving false positives; I am seeing FAIL on headers that I know are sent (via inspection with curl -vvv) and that other tools (I tried https://tools.geekflare.com/tools/x-frame-options-test and it came back ok). Seen with Flask behind an AWS ALB. 

Copy of the headers as see from curl -vvv: 

< HTTP/2 200
< date: Mon, 17 Sep 2018 22:52:13 GMT
< content-type: text/html; charset=utf-8
< content-length: 2103
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< referrer-policy: no-referrer
< server: Werkzeug/0.12.2 Python/3.6.5
<
<!DOCTYPE html>
<html>
... and so on

**Comment by woodruffw** [comment]
I was able to replicate a false negative: it looks like some servers send all of their headers in lowercase in HTTP/2 mode, so the `Location:` extraction in stage 1 was failing. I'll fix that in a moment.

**Comment by bortels** [comment]
Do you have someplace private I can drop the URL? I am looking at this because I am mid-harden, and would rather not present a target to people.

**Comment by bortels** [comment]
ah - We crossed. I will try that...

**Comment by bortels** [comment]
No joy. Same behavior.

**Comment by woodruffw** [comment]
FWIW, I also ran into some problems with `nginx` that were my own doing: If you enable HTTP/2 on `nginx`, make sure to only enable it for your HTTPS ports. I was enabling it on my HTTP redirect ports as well, which was causing it to serve the direct HTTP/2 handshake over HTTP/1.1 with no Upgrade field. That was causing false negatives and unknowns though, not positives, so many unrelated...

**Comment by woodruffw** [comment]
Re: private sharing: I'm yossarian on Keybase if you have that. If not, my PGP key is here: https://keybase.io/yossarian/pgp_keys.asc?fingerprint=46c39716a8f07e98384e28f785ae00c504833b3c

**Comment by woodruffw** [comment]
This is indeed a bug: `twa` was relying on the non-POSIX `IGNORECASE` variable in `awk`, which the macOS (BSD?) `awk` doesn't respect.
