### ISSUE TITLE
CAA test reports "Malformed CAA record?" for some domains that lack CAA records

### ISSUE THREAD

**Issue by vanaltj** [trailofbits/twa#39]
I think this happens when querying a domain that has CNAME and/or default subdomain records.  In those cases, `dig +short caa <domain>` returns some lines that just have the associated records' value.  For example:
`$ dig +short caa example.com
www.example.com.
host1.example.com.`

In this case default subdomain is `www` and there is a CNAME record pointing that at an actual host, but there is no CAA record for any of these.

twa is trying to treat these lines as CAA records:
`UNK(example.com): Malformed CAA record? (flag=www.example.com., tag=, value=)
UNK(example.com): Malformed CAA record? (flag=host1.example.com., tag=, value=)`

**Comment by woodruffw** [comment]
Alright, I was able to reproduce this on developer.mozilla.org:

```bash
$ dig +short caa developer.mozilla.org
mdn-prod.moz.works.
d2jhm933xpgpf7.cloudfront.net.

$ dig caa developer.mozilla.org
;; ANSWER SECTION:
developer.mozilla.org.	31	IN	CNAME	mdn-prod.moz.works.
mdn-prod.moz.works.	31	IN	CNAME	d2jhm933xpgpf7.cloudfront.net.
```

It looks like `dig +noall +answer` is a good solution here:

```bash
$ dig +noall +answer caa developer.mozilla.org
developer.mozilla.org.	56	IN	CNAME	mdn-prod.moz.works.
mdn-prod.moz.works.	55	IN	CNAME	d2jhm933xpgpf7.cloudfront.net.

```
