### ISSUE TITLE
Wiki pages for each TWA-XXYY code

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/twa#40]
Each of these codes needs a wiki page explaining why it exists and how to remedy it. I've gotten the ball rolling with a page for [TWA-0001](https://github.com/trailofbits/twa/wiki/TWA-0001) -- use it as a template for new pages.

* [x] `TWA-0001` "Expected port 443 to be open, but it isn't"
* [x] `TWA-0101` "HTTP redirects to HTTPS using a 302"
* [x] `TWA-0102` "HTTP redirects to HTTP (not secure)"
* [x] `TWA-0103` "HTTP doesn't redirect at all"
* [x] `TWA-0201` "Skipping security checks due to no secure channel"
* [x] `TWA-0202` "Strict-Transport-Security max-age is less than 6 months"
* [x] `TWA-0203` "Strict-Transport-Security, but no includeSubDomains"
* [x] `TWA-0204` "Strict-Transport-Security, but no preload"
* [x] `TWA-0205` "Strict-Transport-Security missing"
* [x] `TWA-0206` "X-Frame-Options is 'sameorigin', consider 'deny'"
* [x] `TWA-0207` "X-Frame-Options is 'allow-from', consider 'deny' or 'none'"
* [x] `TWA-0208` "X-Frame-Options missing"
* [x] `TWA-0209` "X-Content-Type-Options missing"
* [x] `TWA-0210` "X-XSS-Protection is '0'; XSS filtering disabled"
* [x] `TWA-0211` "X-XSS-Protection sanitizes but doesn't block, consider mode=block?"
* [x] `TWA-0212` "X-XSS-Protection missing"
* [x] `TWA-0213` "Referrer-Policy specifies '\${rp}', consider 'no-referrer'?"
* [x] `TWA-0214` "Referrer-Policy missing"
* [x] `TWA-0215` "Content-Security-Policy 'default-src' is '\${csp_default_src}'"
* [x] `TWA-0216` "Content-Security-Policy 'default-src' is missing"
* [x] `TWA-0217` "Content-Security-Policy has one or more 'unsafe-inline' policies"
* [x] `TWA-0218` "Content-Security-Policy has one or more 'unsafe-eval' policies"
* [x] `TWA-0219` "Content-Security-Policy missing"
* [x] `TWA-0220` "Feature-Policy missing"
* [x] `TWA-0301` "Site sends 'Server' with what looks like a version tag: \${server}"
* [x] `TWA-0302` "Site sends a long 'Server', probably disclosing version info: \${server}"
* [x] `TWA-0303` "Site sends '\${badheader}, probably disclosing version info: \${content}'"
* [x] `TWA-0401` "SCM repository being served at: \${url}"
* [x] `TWA-0402` "Possible SCM repository being served (maybe protected?) at: \${url}"
* [x] `TWA-0403` "Environment file being served at: \${url}"
* [x] `TWA-0404` "Possible environment file being served (maybe protected?) at: \${url}"
* [x] `TWA-0405` "Config file being served at: \${url}"
* [x] `TWA-0406` "Possible config file being served (maybe protected?) at: \${url}"
* [x] `TWA-0407` "Package management file being served at: \${url}"
* [x] `TWA-0408` "Possible package management file being served (maybe protected?) at: \${url}"
* [x] `TWA-0409` "Build file being served at: \${url}"
* [x] `TWA-0410` "Possible build file being served (maybe protected?) at: \${url}"
* [x] `TWA-0501` "No robots file found at: \${domain}/robots.txt"
* [x] `TWA-0502` "robots.txt lists what looks like an admin panel"
* [x] `TWA-0503` "robots.txt lists what looks like CGI scripts"
* [x] `TWA-0504` "No security file found at: \${domain}/.well-known/security.txt"
* [x] `TWA-0601` "No CAA records found"
* [x] `TWA-0602` "Domain doesn't specify any valid issuers"
* [x] `TWA-0603` "Domain explicitly disallows all issuers"
* [x] `TWA-0604` "Domain doesn't specify any violation reporting endpoints"
* [x] `TWA-0701` "Domain is listening on a development/backend port: \${dev_port}"
* [x] `TWA-0801` "cookie '\${cookie_name}' has 'secure' but no 'httponly' flag"
* [x] `TWA-0802` "cookie '\${cookie_name}' has no 'secure' flag"

**Comment by ololosha228** [comment]
how i can contribute to this issue? cause i didn't find the way, how to create and edit wiki pages :thinking: :thinking: :thinking:

**Comment by woodruffw** [comment]
You can create and modify wiki pages by going to the "Wiki" tab under the GitHub project and either clicking "New page" or the link to the page you'd like to modify.

**Comment by vsin12** [comment]
As the issue status is open, can I contribute to this ? I am new to open-source and would like to contribute.

**Comment by woodruffw** [comment]
Hi @vsin12. Yes, you're more than welcome to! Please see the comment above for how you can contribute to this particular issue.

**Comment by captn3m0** [comment]
@woodruffw The project's wiki isn't editable by non-contributors.

**Comment by woodruffw** [comment]
> The project's wiki isn't editable by non-contributors.

Whoops, sorry about that. It should be editable now.

**Comment by captn3m0** [comment]
Created pages for HSTS header related codes :+1: 

Will pick up others when I get some free time.

**Comment by woodruffw** [comment]
Just wanted to give a shoutout to @UlrichBerntien for adding a whole bunch of pages. Thank you!

**Comment by woodruffw** [comment]
Updating the list in the README is a little cumbersome, so here are the remaining missing pages:

- [ ] TWA-0806
- [ ] TWA-0807
- [ ] TWA-0808
- [ ] TWA-0809
- [ ] TWA-0810

Once those are added, I'll close this issue out. Future codes will be tracked individually.

**Comment by UlrichBerntien** [comment]
Now all messages were added. I suggest to close this issue.

**Comment by woodruffw** [comment]
Yep. I’ll close it tonight, thanks.
