### ISSUE TITLE
Don't count 301s as serving forbidden content

### ISSUE THREAD

**Issue by petdance** [trailofbits/twa#48]
`twa` complains on my site about serving things like SCM and build files:

```
FAIL(example.com): TWA-0401: SCM repository being served at: http://example.com/.git/HEAD
FAIL(example.com): TWA-0407: Package management file being served at: http://example.com/.npmrc
FAIL(example.com): TWA-0409: Build file being served at: http://example.com/Makefile
```

My site doesn't actually serve content there. It sends a 301 back to the root of the site. It would be nice if twa knew that this wasn't actually serving the forbidden content that it's testing for.

**Comment by woodruffw** [comment]
> It would be nice if twa knew that this wasn't actually serving the forbidden content that it's testing for.

Yep!

The current SCM, etc check logic looks like this:

```bash
    code=$(fetch_respcode "${url}")

    if [[ "${code}" -eq 200 ]]; then
      FAIL TWA-0401
    elif [[ "${code}" -eq 403 ]]; then
      MEH TWA-0402
    elif [[ "${code}" -eq 404 ]]; then
      PASS "No SCM repository at: ${url}"
    else
      UNK "Got a weird response code (${code}) when testing for SCM at: ${url}"
    fi
```

when really we should be checking both `${code}` *and* the redirected path, if it exists, `FAIL`ing or `MEH`ing only if the redirected path hasn't changed.

**Comment by woodruffw** [comment]
@petdance Could you give https://github.com/trailofbits/twa/commit/9656bba7fd897cf4bf496105e7542258e36e053e a try?

**Comment by woodruffw** [comment]
Reproduced and confirmed that patch locally. Thanks for bringing this to my attention!

**Comment by petdance** [comment]
Looks good to me.  Thanks.  👍
