### ISSUE TITLE
Custom user agent

### ISSUE THREAD

**Issue by AyrA** [trailofbits/twa#49]
You should use a custom user agent string that somewhat identifies the toolkit, for example `twa/${TWA_VERSION} +https://github.com/trailofbits/twa`

This can potentially get around the problem of some sites blocking generic curl user agents. It's also nice in general to tell what the source of automated requests is

**Comment by woodruffw** [comment]
(Until I add this, you can use the `TWA_CURLOPTS` environment variable to feed `-A <agent-name>` to `twa`'s curl calls).
