### ISSUE TITLE
Should CAA check recurse?

### ISSUE THREAD

**Issue by AndyA** [trailofbits/twa#50]
According to RFC 6844 a certificate authority should search up the DNS hierarchy for a CAA record:

https://tools.ietf.org/html/rfc6844#page-7

Currently twa only checks the actual domain name.

**Comment by woodruffw** [comment]
Yes, definitely! That's a bug.

I'll get around to it at some point, but a PR would be greatly appreciated 😄

**Comment by AndyA** [comment]
Fixed by cb42a3. Thanks!
