### ISSUE TITLE
Integration with testssl.sh

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/twa#52]
`testssl.sh` is probably a good choice for integration with `twa` for SSL auditing, since it's a single file and doesn't have any non-system dependencies. We should only run it if it's present, emitting an `UNK` and continuing on if it isn't.

Source: https://github.com/drwetter/testssl.sh

**Comment by GatewayBit** [comment]
May I take on this task?

**Comment by woodruffw** [comment]
Go for it!
