### ISSUE TITLE
SameSite checks for cookies

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/twa#56]
We currently check for `secure` and `HttpOnly` on cookies; we should also check the `SameSite` value and emit appropriate results.

Possible results:
* `PASS` for `SameSite=Strict`
* `MEH` for `SameSite=Lax`
* `FAIL` for `SameSite=None`

The absence of `SameSite` currently implies different things on different browsers, so its absence from a cookie should probably be a `MEH` for now.

Resources:
* IETF draft: https://tools.ietf.org/html/draft-west-first-party-cookies-07
* CSRF is (really) dead: https://scotthelme.co.uk/csrf-is-really-dead/

**Comment by GatewayBit** [comment]
I'd like to implement this feature.

**Comment by woodruffw** [comment]
Please do!

**Comment by woodruffw** [comment]
#60.
