### ISSUE TITLE
Cookie prefix checks

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/twa#57]
Similar to #56: Cookie prefixes are another proposed enhancement to cookie security. We should add appropriate checks for `__Host` and `__Secure`.

Resources:
* IETF draft: https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00
* Tough Cookies: https://scotthelme.co.uk/tough-cookies/

**Comment by GatewayBit** [comment]
May I take on this task?

**Comment by woodruffw** [comment]
Yes, please do!
