### ISSUE TITLE
Curious about google example

### ISSUE THREAD

**Issue by luxe** [trailofbits/twa#8]
I'm curious why they are considered failures, if google is not doing them?  Clearly, google must have a reason for failing these tests.  thoughts?

**Comment by woodruffw** [comment]
>  Clearly, google must have a reason for failing these tests. thoughts?

For their `google.com` and `www.google.com` domains, Google has probably decided that their current security features strike a good balance between decent security and development ease/user convenience. I'd imagine that there's a good amount of inertia involved as well.

In general, like the GitHub description says, `twa`'s results should be viewed as (strongly) opinionated: they're what **I** think are the best all-around ways to serve a website securely. Complex websites and large engineering teams can be an obstacle, but I don't think that Google gets a pass for those reasons.

**Comment by woodruffw** [comment]
Yep, @mbitokhov's points are all good. Ultimately, `twa` will probably never be able to (much less attempt to) infer the *intent* of a site, and so any security checks it does will be done in the abstract: it might be the case that Google doesn't need HSTS, but that won't stop `twa` from reporting the absence of HSTS as a failure.

**Comment by woodruffw** [comment]
Closing as answered.
