### ISSUE TITLE
Add more ports to stage 7

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/twa#80]
There are lots of other common development ports that we should check for, including (but not limited to):

- [x] `5000` (Flask and Kestrel's default port)
- [x] `9200` (Elasticsearch's REST API)

**Comment by UlrichBerntien** [comment]
I suggest adding the standard TCP ports of commonly used databases:
-	1433 # Microsoft SQL Server
-	3306 # MySQL and MariaDB
-	3050 # Interbase, Firebird
-	5432 # PostgreSQL
-	6379 # Redis
-	8086 # InfluxDB HTTP service
-	27017 # MongoDB
-	33060 # MySQL X-Protocol

References:
-	[MS SQL](https://docs.microsoft.com/en-us/sql/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access?view=sql-server-ver15)
-	[MySQL](https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html)
-	[Firebird]( https://firebirdsql.org/rlsnotesh/config-port.html)
-	[PostgreSQL](https://www.postgresql.org/docs/11/app-psql.html)
-	[Redis](https://redis.io/topics/quickstart)
-	[InfluxDB](https://docs.influxdata.com/influxdb/v1.8/administration/ports/)
-	[Mongo](https://docs.mongodb.com/manual/reference/default-mongodb-port/)

For a complete port scan specialized tools like nmap should be used. I think to work out a tiny list of typical falsely open ports on web servers should be the aim for the twa script.

**Comment by woodruffw** [comment]
That sounds good to me. I've been on the fence about which ports to add, since `twa` itself (mostly) sticks to HTTP(S)-only issues. But exposed SQL and KV services are a common enough issue that adding them seems reasonable to me.

**Comment by GatewayBit** [comment]
@woodruffw 
May I pickup this task?

**Comment by woodruffw** [comment]
@GatewayBit go for it!

**Comment by UlrichBerntien** [comment]
The issue is more than one month open. I add the ports now to the source.
@GatewayBit If this disturbs your work, please suggest to reject the pull request.

**Comment by GatewayBit** [comment]
@UlrichBerntien Go ahead with this task. Thank you!

**Comment by woodruffw** [comment]
I think #85 covers the majority of the ports I had in mind, so I'm going to close this. We can address additional ports/changes in subsequent issues and PRs.
