### ISSUE TITLE
Github Page Release Web Page UI Revamp

### ISSUE THREAD

**Issue by viiiraj07** [trailofbits/twa#86]
The UI of the main (index.html) web page release looks very undecorated plain. I can revamp the UI using my frontend dev skills without using any external CSS or JS library, only plain HTML, CSS, and JS. Do let me know if I can start working.

Thanks!

**Comment by woodruffw** [comment]
The webpage is generated by `groff` and is intentionally barebones -- it's direct mapping of what you'd get if you ran `man twa` in your terminal.

I'm not opposed to making it easier to read, but that **must** involve an automated tool -- [`roffit`](https://daniel.haxx.se/projects/roffit/) would be a reasonable choice. [Here is an example](https://curl.se/docs/manpage.html) of a page it generates.

**Comment by viiiraj07** [comment]
So, the requirement is to switch from groff generated page to roffit generated page?

**Comment by woodruffw** [comment]
Yes, that would be fine. I'd be happy to merge a PR that switches the generation from `groff` to `roffit`.

**Comment by viiiraj07** [comment]
Sure... I will work on it!

**Comment by viiiraj07** [comment]
@woodruffw please check PR #87
